### ISSUE TITLE
User entity CRUD backend

### ISSUE THREAD

**Issue by justnyx** [kir-dev/mmmk-web#1]
Create the REST API endpoints, that implement CRUD functionality for User objects.

Endpoints:

GET /users

- This should return all the users.
- The backend needs to check if the current user has permission to do it

GET /users/me

- Returns the current user

GET /users/{userId}

- The backend needs to check if the current user has permission to do it

PATCH /users/{userId}

- Modifies a user profile
- The backend needs to check if the current user has permission to do it

**Comment by balintking** [comment]
The auth we're not doing in this iteration, right?
